changelog:
  categories:
    - title: 'Features'
      labels:
        - 'enhancement'
    - title: 'Bug Fixes'
      labels:
        - 'bug'
    - title: 'Documentation'
      labels:
        - 'documentation'
    - title: 'Dependencies'
      labels:
        - 'dependencies'
    - title: 'Other Changes'
      labels:
        - '*'
